// words we block in addition to AlexJS
// please check words are not already covered by AlexJS and the libraries it uses first
// http://alexjs.com
export const BannedWordsOptions = [
  'gys',
  'guyz',
  'guyzz',
  'guyss',
  'boys',
  'bruh',
  'duude',
  'women',
  'sir',
  'sirr',
  'bruhh',
  'man',
  'maan',
  'mann',
  'fellas',
  'madam',
  'maam',
  "ma'am",
  'yessir',
  'chad',
  'simp',
  'simps',
  'simping',
  'mate',
  'matey',
  'mateys',
  'sis',
  'dork',
  'bhaiya',
  'bhai',
];
